-- nvim-treesitter: REMOVED 2026-07-18 (deliberately -- don't re-add casually)
--
-- Why: the plugin's `master` branch froze in March 2026 (final commit
-- cf12346) and is incompatible with Neovim 0.12: core now passes query
-- directives a *list* of nodes per capture, the frozen handler still
-- expects a single node, so every markdown file with a code fence threw
--   "attempt to call method 'range' (a nil value)"
-- from the decoration provider. The plugin's stale queries shadowed
-- Neovim's bundled ones via the runtimepath, so no config knob could
-- fix it -- core auto-starts markdown highlighting itself now
-- ($VIMRUNTIME/ftplugin/markdown.lua is literally `vim.treesitter.start()`).
--
-- What we rely on instead: Neovim 0.12's *bundled* parsers + queries
-- (markdown, markdown_inline, lua, c, vimdoc, query) -- mutually
-- consistent, auto-started by core, code fences included. Everything
-- else falls back to regex syntax highlighting, which we had already
-- disabled treesitter for in the languages that matter here (cpp, r,
-- sql, html...).
--
-- What was lost (knowingly): treesitter textobject keymaps
-- (aa/ia/af/if/ac/ic) and ts-highlighting for python/haskell/js/etc.
-- If wanted back someday: the maintained rewrite is the `main` branch
-- (new setup API, needs `brew install tree-sitter`), plus
-- nvim-treesitter-textobjects' own `main` rewrite for the keymaps.

return {}
